
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

//apps modal api request
export const APP_SAVE_FETCH_STATUS='APP_SAVE_FETCH_STATUS'
export const SAVE_APPS_MODAL= 'SAVE_APPS_MODAL'
export const UPDATE_APPS_STORE_RESULT='UPDATE_APPS_STORE_RESULT'
export const OPEN_APPS_MODAL= 'OPEN_APPS_MODAL'
export const CLOSE_APPS_MODAL= 'CLOSE_APPS_MODAL'
export const SET_TOAST= 'SET_TOAST'

export const PROFILE_SAVE_FETCH_STATUS = 'PROFILE_SAVE_FETCH_STATUS'
export const UPDATE_PROFILE_STORE_RESULT = 'UPDATE_PROFILE_STORE_RESULT'
export const SAVE_PROFILE_DATA= 'SAVE_PROFILE_DATA'
export const OPEN_PROFILE_MODAL= 'OPEN_PROFILE_MODAL'
export const CLOSE_PROFILE_MODAL= 'CLOSE_PROFILE_MODAL'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const INPUT_CHANGE = 'INPUT_CHANGE'
export const MODAL_INPUT_CHANGE = 'MODAL_INPUT_CHANGE'

export const SAVE_USER= 'SAVE_USER'
export const OPEN_REGISTER_MODAL= 'OPEN_REGISTER_MODAL'

export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL'


