
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'


export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const INPUT_CHANGE = 'INPUT_CHANGE'
export const MODAL_INPUT_CHANGE = 'MODAL_INPUT_CHANGE'
export const EDIT_LOGIN_CREDENTIALS = 'EDIT_LOGIN_CREDENTIALS'
export const BACK_BUTTON= 'BACK_BUTTON'
export const ADD_MORE_PARAMS= 'ADD_MORE_PARAMS'
export const NEXT_BUTTON= 'NEXT_BUTTON'


